// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqGArd_kMVRO6UdB67qQNBj4ndtCOgCic',
    appId: '1:244005860949:web:a164d758405ec52f35c6dc',
    messagingSenderId: '244005860949',
    projectId: 'task-management-app-a8f4f',
    authDomain: 'task-management-app-a8f4f.firebaseapp.com',
    storageBucket: 'task-management-app-a8f4f.appspot.com',
    measurementId: 'G-RJ4TRYS3CM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBg-DnLFTjAOVS9iezm-WjWuktC-G_87Fg',
    appId: '1:244005860949:android:076d84ee75f0a30e35c6dc',
    messagingSenderId: '244005860949',
    projectId: 'task-management-app-a8f4f',
    storageBucket: 'task-management-app-a8f4f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDWVZ43MyQk5xRO2S4PQlnbFZqNJSk5ho',
    appId: '1:244005860949:ios:cf24e76d1fd1d35435c6dc',
    messagingSenderId: '244005860949',
    projectId: 'task-management-app-a8f4f',
    storageBucket: 'task-management-app-a8f4f.appspot.com',
    iosBundleId: 'com.example.taskManagementApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDWVZ43MyQk5xRO2S4PQlnbFZqNJSk5ho',
    appId: '1:244005860949:ios:33b521de800a196735c6dc',
    messagingSenderId: '244005860949',
    projectId: 'task-management-app-a8f4f',
    storageBucket: 'task-management-app-a8f4f.appspot.com',
    iosBundleId: 'com.example.taskManagementApp.RunnerTests',
  );
}
